# server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjo4MjQ0bldIWVNOSzJOQU5OaHRfOTZn"
# some random encryption key that we don't want to change between restarts
xpack.security.encryptionKey: "tG0HPMzDMdwXRbhP4i1r7k9vvaqfMLAR"
xpack.encryptedSavedObjects.encryptionKey: "tG0HPMzDMdwXRbhP4i1r7k9vvaqfMLAR"
xpack.reporting.encryptionKey: "tG0HPMzDMdwXRbhP4i1r7k9vvaqfMLAR"
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "30d"